token: "@token@"
base_url: http://apps.syncloud.org
bucket: apps.syncloud.org
aws_access_key_id: "@aws_access_key_id@"
aws_secret_access_key: "@aws_secret_access_key@"
aws_s3_endpoint: https://s3.us-west-2.amazonaws.com
aws_region: us-west-2
